version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8083:3000"  
    environment:
      - DATABASE_URL=postgres://postgres:123@db:5432/cruddb
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cruddb
